### ISSUE TITLE
Refactor: talk 코드 리팩토링

### ISSUE THREAD

**Issue by Ryooon2** [Turing-ForSeason/forseason-BE#2]
## IssueName
Talk 코드 리팩토링 & 리액트 환경 전환
## Description
1. ErrorCode를 이용하여 오류제어 추가
2. 오류 제어가 가능하도록 응답 DTO 수정 (Global하게 적용하여 쓸거임.)
3. 리액트환경에 맞게 RestAPI로 전환
-------------------------------------------------------------------

<STOMP 예외 처리 설명>
1. 클라이언트가 서버로 STOMP 메세지 전송
2. MessagePreHandler가 들어온 메세지를 인터셉트해서 검증 후 Exception 터뜨림
3. StompExceptionHandler가 2번에서 터진 Exception을 바탕으로 ERROR 메세지를 만들어 클라이언트에게 전송

위 기능으로 JWT 인증을 연동 가능해짐
## Todo
--------------------------------------------------------------------
RestAPI
- [x] ErrorCode 정의
- [x] ExceptionHandler 설정
- [x] 정상 응답용 객체 만들기
- [x] 예외 응답용 객체 만들기
- [x]  예외 처리 로직 추가
- [x]  thymleaf환경 메서드 RestAPI로 전환

---------------------------------------------------------------------
메서드 수정 진행 사항
- [x] initUser
- [x] getTalks
- [x] #3
- [x] getUserCount
- [x] getTalkList
- [x] roomDetail
---------------------------------------------------------------------
STOMP API
- [x] ErrorCode 정의
- [x] Stomp 인터셉터 설정
- [x] StompExceptionHandler 설정
- [x]  정상 응답용 객체 만들기
- [x] 예외 응답용 객체 만들기
- [x]  예외 처리 로직 추가
----------------------------------------------------------------------
STOMP 메서드 수정 진행사항
- [x] enterUser
- [x] sendMessage
- [x] webSocketDisconnectListener
