### ISSUE TITLE
feature: 로그인과 talk 서버 로직 연결

### ISSUE THREAD

**Issue by Ryooon2** [Turing-ForSeason/forseason-BE#6]
## IssueName
로그인과 talk 서버 연결 및 디렉토리 구조 조정
## Description
![image](https://github.com/Turing-ForSeason/forseason-BE/assets/138233569/98aeb957-224f-43b3-8f13-f7ebf24d3af5)
기존 디렉토리 구조를 위 사진과 같이 global과 domain으로 나누고, domain은 기능별로 나누었습니다.
global 디렉토리는 ExceptionHandler, Config와 같이 전역적으로 적용될 로직들을 포함하는 디렉토리입니다.

Loign
------------------------------------------------------------------------------------------------

userService에서 getKakaoAccessToken 메서드의 , 리다이렉션 URI를
"http://localhost:8080/api/login/oauth2/code/kakao"에서
"http://localhost:3000/api/login/oauth2/code/kakao"으로 교체했습니다.

++userEntity에 프로필 썸네일로 사용할 thumnail 컬럼을 추가하였습니다.
++반환객체를 ApplicationResponse 객체로 통일하였습니다.

Talk
============================================================

SecurityConfig에서
HttpSecurity.authorizeRequests().antMatchers에 "/stomp/talk/**"를 추가하여, STOMP 소켓연결과정에서의 HTTP 메세지를 JWT필터 대상에서 제외했습니다.(해당 HTTP 메세지를 커스텀할 수 없기 때문.)

MessagePreHandler에서 STOMP 메세지의 헤더부분을 검사해 JWT 토큰 유효성 검사를 하는 로직을 추가하였습니다.

============================================================
JWT 인증 과정에서 발생하는 Exception들을 처리하는 로직을 추가하였습니다.

프론트에서는 
![image](https://github.com/Turing-ForSeason/forseason-BE/assets/138233569/d4798c68-0fae-41bd-94a5-9e3c00e193eb)
위 사진의 catch 부분과 같이 예외를 처리하시면 됩니다.

## Todo
- [x] thumnail columm 추가
- [x] 리다이렉션 URI 변경
- [x] 디렉토리 구조 변경
- [x] talk JWT 토큰 유효성 검사 추가
- [x] talk stomp endpoint JWT 필터에서 제외
- [x] 로그인 Controller 반환객체 수정
- [x] ExceptionHandler 통합
- [x] 예외처리 로직 추가
